# Generated by Django 4.1 on 2022-09-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_status_todo_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='data_criacao',
        ),
    ]
