# Generated by Django 4.1 on 2022-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_todo_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
